// 食物数据库 - 包含中国人常见饮食
const FOOD_DB = [
  // 早餐类
  { name: "肉包", category: "早餐", calorie: 220, nutrients: { protein: 8, carb: 35, fat: 6 } },
  { name: "粉丝包", category: "早餐", calorie: 190, nutrients: { protein: 5, carb: 38, fat: 2 } },
  { name: "青菜包", category: "早餐", calorie: 180, nutrients: { protein: 4, carb: 37, fat: 2 } },
  { name: "豆沙包", category: "早餐", calorie: 210, nutrients: { protein: 5, carb: 42, fat: 3 } },
  { name: "奶黄包", category: "早餐", calorie: 230, nutrients: { protein: 5, carb: 40, fat: 7 } },
  { name: "小笼包", category: "早餐", calorie: 250, nutrients: { protein: 10, carb: 30, fat: 10 } },
  { name: "油条", category: "早餐", calorie: 380, nutrients: { protein: 6, carb: 49, fat: 19 } },
  { name: "豆浆", category: "早餐", calorie: 15, nutrients: { protein: 1.8, carb: 1.1, fat: 0.7 } },
  { name: "纯牛奶", category: "早餐", calorie: 54, nutrients: { protein: 3.2, carb: 3.4, fat: 3.2 } },
  { name: "水煮蛋", category: "早餐", calorie: 143, nutrients: { protein: 13, carb: 1, fat: 10 } },
  { name: "全麦面包", category: "早餐", calorie: 250, nutrients: { protein: 12, carb: 45, fat: 3 } },
  { name: "燕麦片", category: "早餐", calorie: 389, nutrients: { protein: 16, carb: 66, fat: 6.9 } },
  { name: "蒸饺", category: "早餐", calorie: 280, nutrients: { protein: 12, carb: 25, fat: 14 } },
  { name: "烧麦", category: "早餐", calorie: 260, nutrients: { protein: 7, carb: 35, fat: 9 } },
  { name: "手抓饼", category: "早餐", calorie: 300, nutrients: { protein: 6, carb: 35, fat: 15 } },
  { name: "皮蛋瘦肉粥", category: "早餐", calorie: 90, nutrients: { protein: 4, carb: 15, fat: 2 } },
  { name: "小米粥", category: "早餐", calorie: 46, nutrients: { protein: 1.4, carb: 10, fat: 0.7 } },
  { name: "玉米粥", category: "早餐", calorie: 40, nutrients: { protein: 1, carb: 8, fat: 0.3 } },
  { name: "豆沙粽", category: "早餐", calorie: 340, nutrients: { protein: 6, carb: 70, fat: 4 } },
  { name: "肉粽", category: "早餐", calorie: 350, nutrients: { protein: 10, carb: 60, fat: 10 } },
  { name: "煎蛋", category: "早餐", calorie: 185, nutrients: { protein: 13, carb: 1, fat: 14 } },
  { name: "肉松面包", category: "早餐", calorie: 320, nutrients: { protein: 8, carb: 45, fat: 12 } },
  { name: "华夫饼", category: "早餐", calorie: 310, nutrients: { protein: 6, carb: 40, fat: 12 } },
  { name: "蒸红薯", category: "早餐", calorie: 86, nutrients: { protein: 1.6, carb: 20, fat: 0.1 } },
  { name: "蒸玉米", category: "早餐", calorie: 116, nutrients: { protein: 4.0, carb: 25, fat: 1.2 } },
  { name: "水煮玉米", category: "早餐", calorie: 106, nutrients: { protein: 3.6, carb: 23, fat: 1.1 } },
  { name: "豆沙饼", category: "早餐", calorie: 290, nutrients: { protein: 6, carb: 50, fat: 8 } },
  { name: "葱油饼", category: "早餐", calorie: 320, nutrients: { protein: 7, carb: 38, fat: 15 } },
  { name: "豆腐脑", category: "早餐", calorie: 40, nutrients: { protein: 4, carb: 2, fat: 2 } },
  { name: "胡辣汤", category: "早餐", calorie: 90, nutrients: { protein: 3, carb: 15, fat: 2 } },
  { name: "芝麻糊", category: "早餐", calorie: 380, nutrients: { protein: 8, carb: 70, fat: 6 } },
  { name: "藕粉", category: "早餐", calorie: 373, nutrients: { protein: 0.2, carb: 93, fat: 0.1 } },
  { name: "蜂蜜蛋糕", category: "早餐", calorie: 320, nutrients: { protein: 7, carb: 45, fat: 12 } },
  { name: "鸡蛋灌饼", category: "早餐", calorie: 300, nutrients: { protein: 8, carb: 35, fat: 12 } },
  { name: "煎饼", category: "早餐", calorie: 290, nutrients: { protein: 6, carb: 38, fat: 10 } },
  { name: "包子", category: "早餐", calorie: 220, nutrients: { protein: 8, carb: 35, fat: 6 } },
  { name: "花卷", category: "早餐", calorie: 217, nutrients: { protein: 7, carb: 40, fat: 2 } },
  { name: "馒头", category: "早餐", calorie: 221, nutrients: { protein: 7, carb: 43, fat: 1 } },
  { name: "烙饼", category: "早餐", calorie: 250, nutrients: { protein: 7, carb: 38, fat: 8 } },
  { name: "窝窝头", category: "早餐", calorie: 112, nutrients: { protein: 4, carb: 22, fat: 1 } },
  { name: "南瓜饼", category: "早餐", calorie: 266, nutrients: { protein: 6, carb: 38, fat: 12 } },
  
  // 主食类
  { name: "白米饭", category: "主食", calorie: 116, nutrients: { protein: 2.6, carb: 25.6, fat: 0.3 } },
  { name: "火鸡面", category: "主食", calorie: 500, nutrients: { protein: 10, carb: 70, fat: 15 } },
  { name: "挂面", category: "主食", calorie: 345, nutrients: { protein: 10, carb: 75, fat: 1 } },
  { name: "白馒头", category: "主食", calorie: 280, nutrients: { protein: 8, carb: 55, fat: 1 } },
  { name: "红薯", category: "主食", calorie: 86, nutrients: { protein: 1.6, carb: 20, fat: 0.1 } },
  { name: "玉米", category: "主食", calorie: 116, nutrients: { protein: 4.0, carb: 25, fat: 1.2 } },
  { name: "紫薯", category: "主食", calorie: 77, nutrients: { protein: 2.3, carb: 17, fat: 0.2 } },
  { name: "意大利面", category: "主食", calorie: 350, nutrients: { protein: 12, carb: 75, fat: 1.5 } },
  { name: "荞麦面", category: "主食", calorie: 340, nutrients: { protein: 11, carb: 70, fat: 2 } },
  { name: "黑米米饭", category: "主食", calorie: 110, nutrients: { protein: 3.3, carb: 24, fat: 0.3 } },
  { name: "糙米米饭", category: "主食", calorie: 112, nutrients: { protein: 2.8, carb: 23, fat: 0.8 } },
  { name: "手擀面", category: "主食", calorie: 300, nutrients: { protein: 10, carb: 60, fat: 2 } },
  { name: "炒面", category: "主食", calorie: 150, nutrients: { protein: 5, carb: 25, fat: 3 } },
  { name: "焖面", category: "主食", calorie: 180, nutrients: { protein: 6, carb: 30, fat: 4 } },
  { name: "蒸米饭", category: "主食", calorie: 115, nutrients: { protein: 2.6, carb: 25, fat: 0.3 } },
  { name: "糯米饭", category: "主食", calorie: 116, nutrients: { protein: 2.4, carb: 26, fat: 0.2 } },
  { name: "小米饭", category: "主食", calorie: 116, nutrients: { protein: 4.8, carb: 23, fat: 0.7 } },
  { name: "燕麦饭", category: "主食", calorie: 130, nutrients: { protein: 5, carb: 26, fat: 2 } },
  { name: "青稞饭", category: "主食", calorie: 120, nutrients: { protein: 8, carb: 22, fat: 2 } },
  { name: "藜麦饭", category: "主食", calorie: 120, nutrients: { protein: 4.4, carb: 22, fat: 1.4 } },
  { name: "炒饭", category: "主食", calorie: 180, nutrients: { protein: 6, carb: 25, fat: 6 } },
  { name: "烩饭", category: "主食", calorie: 160, nutrients: { protein: 5, carb: 25, fat: 4 } },
  { name: "竹筒饭", category: "主食", calorie: 120, nutrients: { protein: 3, carb: 25, fat: 1 } },
  { name: "紫米饭", category: "主食", calorie: 115, nutrients: { protein: 3, carb: 24, fat: 0.3 } },
  { name: "杂粮饭", category: "主食", calorie: 110, nutrients: { protein: 3.5, carb: 22, fat: 0.5 } },
  { name: "南瓜饭", category: "主食", calorie: 100, nutrients: { protein: 3, carb: 20, fat: 0.3 } },
  { name: "八宝粥", category: "主食", calorie: 70, nutrients: { protein: 2, carb: 15, fat: 0.5 } },
  { name: "绿豆粥", category: "主食", calorie: 46, nutrients: { protein: 1.5, carb: 10, fat: 0.1 } },
  { name: "红豆粥", category: "主食", calorie: 56, nutrients: { protein: 2, carb: 12, fat: 0.1 } },
  { name: "腊八粥", category: "主食", calorie: 90, nutrients: { protein: 3, carb: 18, fat: 0.5 } },
  { name: "年糕", category: "主食", calorie: 154, nutrients: { protein: 3.3, carb: 34.7, fat: 0.6 } },
  { name: "糍粑", category: "主食", calorie: 257, nutrients: { protein: 3, carb: 50, fat: 5 } },
  { name: "粽子", category: "主食", calorie: 148, nutrients: { protein: 4, carb: 30, fat: 2 } },
  { name: "汤圆", category: "主食", calorie: 180, nutrients: { protein: 3, carb: 35, fat: 3 } },
  { name: "饺子", category: "主食", calorie: 70, nutrients: { protein: 3, carb: 8, fat: 3 } },
  { name: "馄饨", category: "主食", calorie: 55, nutrients: { protein: 2.5, carb: 6, fat: 2 } },
  { name: "包子", category: "主食", calorie: 220, nutrients: { protein: 8, carb: 35, fat: 6 } },
  { name: "花卷", category: "主食", calorie: 217, nutrients: { protein: 7, carb: 40, fat: 2 } },
  { name: "窝窝头", category: "主食", calorie: 112, nutrients: { protein: 4, carb: 22, fat: 1 } },
  { name: "烙饼", category: "主食", calorie: 250, nutrients: { protein: 7, carb: 38, fat: 8 } },
  
  // 肉类
  { name: "鸡胸肉", category: "肉类", calorie: 118, nutrients: { protein: 24, carb: 0, fat: 2.6 } },
  { name: "瘦牛肉", category: "肉类", calorie: 105, nutrients: { protein: 26, carb: 0, fat: 1.8 } },
  { name: "瘦猪肉", category: "肉类", calorie: 143, nutrients: { protein: 20.3, carb: 1.5, fat: 6.2 } },
  { name: "羊肉", category: "肉类", calorie: 118, nutrients: { protein: 20.5, carb: 0, fat: 3.9 } },
  { name: "三文鱼", category: "肉类", calorie: 139, nutrients: { protein: 20.4, carb: 0, fat: 7.3 } },
  { name: "虾", category: "肉类", calorie: 93, nutrients: { protein: 20.6, carb: 0.7, fat: 0.7 } },
  { name: "培根", category: "肉类", calorie: 391, nutrients: { protein: 20.4, carb: 1.4, fat: 37.3 } },
  { name: "火腿", category: "肉类", calorie: 330, nutrients: { protein: 15, carb: 4, fat: 29 } },
  { name: "鸡翅", category: "肉类", calorie: 194, nutrients: { protein: 17.4, carb: 0.7, fat: 13.6 } },
  { name: "鸡腿", category: "肉类", calorie: 181, nutrients: { protein: 16, carb: 0, fat: 13 } },
  { name: "鸭胸肉", category: "肉类", calorie: 91, nutrients: { protein: 19.2, carb: 0, fat: 1.5 } },
  { name: "猪肝", category: "肉类", calorie: 129, nutrients: { protein: 19.3, carb: 5, fat: 3.5 } },
  { name: "猪里脊", category: "肉类", calorie: 105, nutrients: { protein: 20.2, carb: 0, fat: 3.4 } },
  { name: "牛里脊", category: "肉类", calorie: 105, nutrients: { protein: 25, carb: 0, fat: 2 } },
  { name: "带鱼", category: "肉类", calorie: 127, nutrients: { protein: 18.4, carb: 0, fat: 4.9 } },
  { name: "黄花鱼", category: "肉类", calorie: 99, nutrients: { protein: 17.9, carb: 0.1, fat: 3 } },
  { name: "鳕鱼", category: "肉类", calorie: 88, nutrients: { protein: 20.4, carb: 0, fat: 0.5 } },
  { name: "鱿鱼", category: "肉类", calorie: 75, nutrients: { protein: 17, carb: 0, fat: 0.8 } },
  { name: "章鱼", category: "肉类", calorie: 52, nutrients: { protein: 10.6, carb: 0, fat: 0.4 } },
  { name: "扇贝", category: "肉类", calorie: 60, nutrients: { protein: 11.1, carb: 2.6, fat: 0.6 } },
  { name: "生蚝", category: "肉类", calorie: 56, nutrients: { protein: 10.9, carb: 3.6, fat: 1.5 } },
  { name: "午餐肉", category: "肉类", calorie: 229, nutrients: { protein: 10, carb: 2, fat: 20 } },
  { name: "香肠", category: "肉类", calorie: 212, nutrients: { protein: 11, carb: 4, fat: 18 } },
  { name: "腊肠", category: "肉类", calorie: 584, nutrients: { protein: 16, carb: 11, fat: 55 } },
  { name: "牛肉丸", category: "肉类", calorie: 107, nutrients: { protein: 12, carb: 3, fat: 7 } },
  { name: "鱼丸", category: "肉类", calorie: 73, nutrients: { protein: 7, carb: 8, fat: 3 } },
  { name: "鸭腿", category: "肉类", calorie: 210, nutrients: { protein: 15, carb: 0, fat: 16 } },
  { name: "鸭肉", category: "肉类", calorie: 240, nutrients: { protein: 15, carb: 0, fat: 20 } },
  { name: "鹅肉", category: "肉类", calorie: 247, nutrients: { protein: 17.9, carb: 0, fat: 19.9 } },
  { name: "兔肉", category: "肉类", calorie: 105, nutrients: { protein: 21.2, carb: 0.9, fat: 2.2 } },
  { name: "鸽子肉", category: "肉类", calorie: 141, nutrients: { protein: 20.9, carb: 0.3, fat: 7.9 } },
  { name: "鹌鹑蛋", category: "肉类", calorie: 160, nutrients: { protein: 12.8, carb: 1.1, fat: 11.1 } },
  { name: "鸡蛋", category: "肉类", calorie: 143, nutrients: { protein: 13, carb: 1, fat: 10 } },
  { name: "鸭蛋", category: "肉类", calorie: 180, nutrients: { protein: 12.6, carb: 3.1, fat: 13 } },
  { name: "鹅蛋", category: "肉类", calorie: 196, nutrients: { protein: 11.1, carb: 2.8, fat: 15.6 } },
  { name: "鱼翅", category: "肉类", calorie: 124, nutrients: { protein: 83, carb: 0, fat: 0.3 } },
  { name: "海参", category: "肉类", calorie: 78, nutrients: { protein: 16.5, carb: 0, fat: 0.2 } },
  { name: "鲍鱼", category: "肉类", calorie: 84, nutrients: { protein: 19, carb: 1.5, fat: 0.8 } },
  { name: "蟹肉", category: "肉类", calorie: 95, nutrients: { protein: 18.1, carb: 1.1, fat: 2.1 } },
  { name: "螺肉", category: "肉类", calorie: 60, nutrients: { protein: 11, carb: 2, fat: 1 } },
  
  // 蔬菜类
  { name: "菠菜", category: "蔬菜", calorie: 28, nutrients: { protein: 2.9, carb: 4.5, fat: 0.4 } },
  { name: "西兰花", category: "蔬菜", calorie: 34, nutrients: { protein: 2.8, carb: 6.6, fat: 0.4 } },
  { name: "黄瓜", category: "蔬菜", calorie: 16, nutrients: { protein: 0.8, carb: 3.6, fat: 0.1 } },
  { name: "番茄", category: "蔬菜", calorie: 15, nutrients: { protein: 0.9, carb: 3.9, fat: 0.2 } },
  { name: "生菜", category: "蔬菜", calorie: 16, nutrients: { protein: 1.3, carb: 2.2, fat: 0.2 } },
  { name: "芹菜", category: "蔬菜", calorie: 17, nutrients: { protein: 0.7, carb: 3.1, fat: 0.2 } },
  { name: "胡萝卜", category: "蔬菜", calorie: 41, nutrients: { protein: 0.9, carb: 9.6, fat: 0.2 } },
  { name: "冬瓜", category: "蔬菜", calorie: 12, nutrients: { protein: 0.4, carb: 2.4, fat: 0.2 } },
  { name: "南瓜", category: "蔬菜", calorie: 26, nutrients: { protein: 1.0, carb: 6.5, fat: 0.1 } },
  { name: "茄子", category: "蔬菜", calorie: 21, nutrients: { protein: 1.1, carb: 4.9, fat: 0.2 } },
  { name: "青椒", category: "蔬菜", calorie: 22, nutrients: { protein: 0.9, carb: 5.4, fat: 0.2 } },
  { name: "洋葱", category: "蔬菜", calorie: 40, nutrients: { protein: 1.1, carb: 9.3, fat: 0.1 } },
  { name: "土豆", category: "蔬菜", calorie: 77, nutrients: { protein: 2.0, carb: 17.4, fat: 0.1 } },
  { name: "山药", category: "蔬菜", calorie: 57, nutrients: { protein: 1.9, carb: 12.4, fat: 0.2 } },
  { name: "莲藕", category: "蔬菜", calorie: 70, nutrients: { protein: 1.9, carb: 16.4, fat: 0.2 } },
  { name: "豆芽", category: "蔬菜", calorie: 18, nutrients: { protein: 2.1, carb: 2.8, fat: 0.1 } },
  { name: "金针菇", category: "蔬菜", calorie: 32, nutrients: { protein: 2.4, carb: 6.0, fat: 0.4 } },
  { name: "香菇", category: "蔬菜", calorie: 26, nutrients: { protein: 2.2, carb: 5.2, fat: 0.3 } },
  { name: "平菇", category: "蔬菜", calorie: 24, nutrients: { protein: 1.9, carb: 4.6, fat: 0.3 } },
  { name: "白菜", category: "蔬菜", calorie: 17, nutrients: { protein: 1.5, carb: 3.2, fat: 0.1 } },
  { name: "娃娃菜", category: "蔬菜", calorie: 12, nutrients: { protein: 1.0, carb: 2.5, fat: 0.1 } },
  { name: "油菜", category: "蔬菜", calorie: 23, nutrients: { protein: 1.8, carb: 3.8, fat: 0.5 } },
  { name: "韭菜", category: "蔬菜", calorie: 26, nutrients: { protein: 2.4, carb: 4.6, fat: 0.4 } },
  { name: "空心菜", category: "蔬菜", calorie: 20, nutrients: { protein: 2.2, carb: 3.6, fat: 0.3 } },
  { name: "豆角", category: "蔬菜", calorie: 30, nutrients: { protein: 2.4, carb: 6.7, fat: 0.2 } },
  { name: "四季豆", category: "蔬菜", calorie: 28, nutrients: { protein: 2.0, carb: 5.7, fat: 0.2 } },
  { name: "荷兰豆", category: "蔬菜", calorie: 27, nutrients: { protein: 2.5, carb: 4.7, fat: 0.3 } },
  { name: "芦笋", category: "蔬菜", calorie: 22, nutrients: { protein: 2.2, carb: 3.8, fat: 0.2 } },
  { name: "生菜", category: "蔬菜", calorie: 16, nutrients: { protein: 1.3, carb: 2.2, fat: 0.2 } },
  { name: "油麦菜", category: "蔬菜", calorie: 15, nutrients: { protein: 1.4, carb: 1.8, fat: 0.2 } },
  { name: "茼蒿", category: "蔬菜", calorie: 21, nutrients: { protein: 1.9, carb: 2.4, fat: 0.3 } },
  { name: "雪里蕻", category: "蔬菜", calorie: 25, nutrients: { protein: 2.9, carb: 4.7, fat: 0.4 } },
  { name: "苋菜", category: "蔬菜", calorie: 25, nutrients: { protein: 2.8, carb: 5.9, fat: 0.3 } },
  { name: "芥蓝", category: "蔬菜", calorie: 19, nutrients: { protein: 1.5, carb: 3.6, fat: 0.4 } },
  { name: "西兰花", category: "蔬菜", calorie: 34, nutrients: { protein: 2.8, carb: 6.6, fat: 0.4 } },
  { name: "花椰菜", category: "蔬菜", calorie: 34, nutrients: { protein: 2.8, carb: 6.6, fat: 0.4 } },
  { name: "西洋菜", category: "蔬菜", calorie: 17, nutrients: { protein: 2.3, carb: 2.2, fat: 0.4 } },
  { name: "苦苣", category: "蔬菜", calorie: 17, nutrients: { protein: 1.8, carb: 3.6, fat: 0.2 } },
  { name: "紫甘蓝", category: "蔬菜", calorie: 32, nutrients: { protein: 1.2, carb: 7.6, fat: 0.2 } },
  { name: "圆白菜", category: "蔬菜", calorie: 24, nutrients: { protein: 1.5, carb: 5.4, fat: 0.2 } },
  
  // 水果类
  { name: "苹果", category: "水果", calorie: 52, nutrients: { protein: 0.3, carb: 13.8, fat: 0.2 } },
  { name: "香蕉", category: "水果", calorie: 93, nutrients: { protein: 1.1, carb: 22.8, fat: 0.3 } },
  { name: "橙子", category: "水果", calorie: 47, nutrients: { protein: 0.9, carb: 11.8, fat: 0.1 } },
  { name: "草莓", category: "水果", calorie: 32, nutrients: { protein: 0.7, carb: 7.7, fat: 0.3 } },
  { name: "蓝莓", category: "水果", calorie: 57, nutrients: { protein: 0.7, carb: 14.5, fat: 0.3 } },
  { name: "西瓜", category: "水果", calorie: 30, nutrients: { protein: 0.6, carb: 7.6, fat: 0.1 } },
  { name: "芒果", category: "水果", calorie: 65, nutrients: { protein: 0.8, carb: 17, fat: 0.3 } },
  { name: "猕猴桃", category: "水果", calorie: 56, nutrients: { protein: 1.1, carb: 14.5, fat: 0.6 } },
  { name: "梨", category: "水果", calorie: 44, nutrients: { protein: 0.4, carb: 10.2, fat: 0.2 } },
  { name: "葡萄", category: "水果", calorie: 45, nutrients: { protein: 0.7, carb: 10.9, fat: 0.2 } },
  { name: "柚子", category: "水果", calorie: 41, nutrients: { protein: 0.8, carb: 9.5, fat: 0.2 } },
  { name: "橘子", category: "水果", calorie: 43, nutrients: { protein: 0.9, carb: 10.2, fat: 0.1 } },
  { name: "菠萝", category: "水果", calorie: 44, nutrients: { protein: 0.5, carb: 10.9, fat: 0.1 } },
  { name: "桃子", category: "水果", calorie: 41, nutrients: { protein: 0.9, carb: 9.5, fat: 0.2 } },
  { name: "李子", category: "水果", calorie: 36, nutrients: { protein: 0.7, carb: 8.7, fat: 0.2 } },
  { name: "杏", category: "水果", calorie: 36, nutrients: { protein: 0.9, carb: 9.1, fat: 0.1 } },
  { name: "樱桃", category: "水果", calorie: 46, nutrients: { protein: 1.1, carb: 10.6, fat: 0.2 } },
  { name: "荔枝", category: "水果", calorie: 70, nutrients: { protein: 0.9, carb: 16.6, fat: 0.2 } },
  { name: "龙眼", category: "水果", calorie: 71, nutrients: { protein: 1.2, carb: 16.6, fat: 0.1 } },
  { name: "榴莲", category: "水果", calorie: 147, nutrients: { protein: 2.6, carb: 28.3, fat: 5.3 } },
  { name: "山竹", category: "水果", calorie: 69, nutrients: { protein: 0.4, carb: 17.5, fat: 0.2 } },
  { name: "牛油果", category: "水果", calorie: 160, nutrients: { protein: 2, carb: 9, fat: 14.7 } },
  { name: "椰子", category: "水果", calorie: 231, nutrients: { protein: 3.3, carb: 15.2, fat: 23.8 } },
  { name: "百香果", category: "水果", calorie: 97, nutrients: { protein: 2.2, carb: 23.3, fat: 0.7 } },
  { name: "火龙果", category: "水果", calorie: 51, nutrients: { protein: 1.1, carb: 13.3, fat: 0.2 } },
  { name: "哈密瓜", category: "水果", calorie: 34, nutrients: { protein: 0.5, carb: 8.5, fat: 0.1 } },
  { name: "甜瓜", category: "水果", calorie: 26, nutrients: { protein: 0.4, carb: 6.2, fat: 0.1 } },
  { name: "香瓜", category: "水果", calorie: 30, nutrients: { protein: 0.4, carb: 7.6, fat: 0.1 } },
  { name: "沙糖桔", category: "水果", calorie: 42, nutrients: { protein: 0.6, carb: 10.3, fat: 0.1 } },
  { name: "蜜橘", category: "水果", calorie: 43, nutrients: { protein: 0.8, carb: 10.3, fat: 0.1 } },
  { name: "金桔", category: "水果", calorie: 53, nutrients: { protein: 1.0, carb: 13.7, fat: 0.2 } },
  { name: "柠檬", category: "水果", calorie: 29, nutrients: { protein: 1.1, carb: 9.3, fat: 0.3 } },
  { name: "柚子", category: "水果", calorie: 41, nutrients: { protein: 0.8, carb: 9.5, fat: 0.2 } },
  { name: "石榴", category: "水果", calorie: 83, nutrients: { protein: 1.5, carb: 18.7, fat: 0.4 } },
  { name: "山楂", category: "水果", calorie: 95, nutrients: { protein: 0.5, carb: 25.1, fat: 0.6 } },
  { name: "海棠果", category: "水果", calorie: 73, nutrients: { protein: 0.3, carb: 19.2, fat: 0.2 } },
  { name: "红枣", category: "水果", calorie: 125, nutrients: { protein: 1.1, carb: 32.6, fat: 0.2 } },
  { name: "黑枣", category: "水果", calorie: 228, nutrients: { protein: 3.7, carb: 52.2, fat: 0.5 } },
  { name: "柿饼", category: "水果", calorie: 250, nutrients: { protein: 1.8, carb: 62.8, fat: 0.5 } },
  
  // 快餐类
  { name: "临榆炸鸡腿", category: "快餐", calorie: 270, nutrients: { protein: 15, carb: 12, fat: 18 } },
  { name: "芝士披萨", category: "快餐", calorie: 280, nutrients: { protein: 12, carb: 30, fat: 12 } },
  { name: "牛肉汉堡", category: "快餐", calorie: 250, nutrients: { protein: 15, carb: 28, fat: 10 } },
  { name: "薯条", category: "快餐", calorie: 298, nutrients: { protein: 3, carb: 36, fat: 17 } },
  { name: "原味炸鸡", category: "快餐", calorie: 270, nutrients: { protein: 14, carb: 11, fat: 19 } },
  { name: "可乐", category: "快餐", calorie: 42, nutrients: { protein: 0, carb: 11, fat: 0 } },
  { name: "珍珠奶茶", category: "快餐", calorie: 100, nutrients: { protein: 2, carb: 20, fat: 2 } },
  { name: "香辣鸡翅", category: "快餐", calorie: 240, nutrients: { protein: 13, carb: 10, fat: 17 } },
  { name: "上校鸡块", category: "快餐", calorie: 260, nutrients: { protein: 12, carb: 15, fat: 16 } },
  { name: "鸡排", category: "快餐", calorie: 250, nutrients: { protein: 16, carb: 12, fat: 15 } },
  { name: "热狗", category: "快餐", calorie: 250, nutrients: { protein: 10, carb: 25, fat: 12 } },
  { name: "蛋挞", category: "快餐", calorie: 375, nutrients: { protein: 6, carb: 30, fat: 27 } },
  { name: "甜筒冰淇淋", category: "快餐", calorie: 150, nutrients: { protein: 3, carb: 20, fat: 7 } },
  { name: "炸鸡排", category: "快餐", calorie: 280, nutrients: { protein: 17, carb: 14, fat: 18 } },
  { name: "汉堡胚", category: "快餐", calorie: 250, nutrients: { protein: 8, carb: 45, fat: 5 } },
  { name: "番茄酱", category: "快餐", calorie: 80, nutrients: { protein: 1, carb: 19, fat: 0 } },
  { name: "沙拉酱", category: "快餐", calorie: 490, nutrients: { protein: 0, carb: 4, fat: 55 } },
  { name: "炸鸡柳", category: "快餐", calorie: 260, nutrients: { protein: 14, carb: 15, fat: 16 } },
  { name: "炸薯条", category: "快餐", calorie: 300, nutrients: { protein: 4, carb: 37, fat: 18 } },
  { name: "芝士汉堡", category: "快餐", calorie: 300, nutrients: { protein: 15, carb: 32, fat: 14 } },
  { name: "鸡肉卷", category: "快餐", calorie: 250, nutrients: { protein: 12, carb: 28, fat: 10 } },
  { name: "墨西哥卷饼", category: "快餐", calorie: 270, nutrients: { protein: 13, carb: 30, fat: 12 } },
  { name: "寿司", category: "快餐", calorie: 100, nutrients: { protein: 4, carb: 18, fat: 1 } },
  { name: "饭团", category: "快餐", calorie: 120, nutrients: { protein: 3, carb: 25, fat: 1 } },
  { name: "三明治", category: "快餐", calorie: 250, nutrients: { protein: 10, carb: 30, fat: 10 } },
  { name: "热狗肠", category: "快餐", calorie: 307, nutrients: { protein: 11, carb: 3, fat: 28 } },
  { name: "烤肠", category: "快餐", calorie: 307, nutrients: { protein: 11, carb: 3, fat: 28 } },
  { name: "薯片", category: "快餐", calorie: 536, nutrients: { protein: 7, carb: 53, fat: 35 } },
  { name: "爆米花", category: "快餐", calorie: 387, nutrients: { protein: 12, carb: 78, fat: 4 } },
  { name: "奶茶", category: "快餐", calorie: 50, nutrients: { protein: 1, carb: 10, fat: 1 } },
  { name: "果汁", category: "快餐", calorie: 45, nutrients: { protein: 0, carb: 11, fat: 0 } },
  { name: "雪碧", category: "快餐", calorie: 43, nutrients: { protein: 0, carb: 11, fat: 0 } },
  { name: "美年达", category: "快餐", calorie: 43, nutrients: { protein: 0, carb: 11, fat: 0 } },
  { name: "芬达", category: "快餐", calorie: 43, nutrients: { protein: 0, carb: 11, fat: 0 } },
  { name: "冰红茶", category: "快餐", calorie: 37, nutrients: { protein: 0, carb: 9, fat: 0 } },
  { name: "绿茶", category: "快餐", calorie: 16, nutrients: { protein: 0, carb: 4, fat: 0 } },
  { name: "冰咖啡", category: "快餐", calorie: 2, nutrients: { protein: 0, carb: 0, fat: 0 } },
  { name: "热咖啡", category: "快餐", calorie: 2, nutrients: { protein: 0, carb: 0, fat: 0 } },
  { name: "拿铁咖啡", category: "快餐", calorie: 106, nutrients: { protein: 6, carb: 12, fat: 4 } },
  { name: "卡布奇诺", category: "快餐", calorie: 70, nutrients: { protein: 3, carb: 9, fat: 2 } },
  { name: "摩卡咖啡", category: "快餐", calorie: 247, nutrients: { protein: 8, carb: 32, fat: 8 } },
  // 沙县小吃 - 主食套餐类
  { name: "沙县鸡腿饭", category: "沙县小吃", calorie: 185, nutrients: { protein: 12, carb: 25, fat: 5 } },
  { name: "沙县鸭腿饭", category: "沙县小吃", calorie: 190, nutrients: { protein: 11, carb: 26, fat: 6 } },
  { name: "沙县卤肉饭", category: "沙县小吃", calorie: 178, nutrients: { protein: 10, carb: 24, fat: 7 } },
  { name: "沙县红烧肉饭", category: "沙县小吃", calorie: 210, nutrients: { protein: 13, carb: 25, fat: 9 } },
  { name: "沙县梅菜扣肉饭", category: "沙县小吃", calorie: 205, nutrients: { protein: 12, carb: 24, fat: 8 } },
  { name: "沙县香菇滑鸡饭", category: "沙县小吃", calorie: 165, nutrients: { protein: 10, carb: 22, fat: 5 } },
  { name: "沙县小炒肉饭", category: "沙县小吃", calorie: 172, nutrients: { protein: 11, carb: 23, fat: 6 } },
  { name: "沙县酸辣土豆丝饭", category: "沙县小吃", calorie: 150, nutrients: { protein: 8, carb: 28, fat: 3 } },
  { name: "沙县青椒肉丝饭", category: "沙县小吃", calorie: 168, nutrients: { protein: 10, carb: 25, fat: 5 } },
  { name: "沙县鱼香肉丝饭", category: "沙县小吃", calorie: 175, nutrients: { protein: 11, carb: 26, fat: 6 } },
  // 沙县小吃 - 汤品类
  { name: "沙县扁食汤", category: "沙县小吃", calorie: 85, nutrients: { protein: 8, carb: 8, fat: 3 } },
  { name: "沙县馄饨汤", category: "沙县小吃", calorie: 80, nutrients: { protein: 7, carb: 7, fat: 3 } },
  { name: "沙县炖罐-茶树菇排骨汤", category: "沙县小吃", calorie: 95, nutrients: { protein: 15, carb: 3, fat: 3 } },
  { name: "沙县炖罐-天麻乌鸡汤", category: "沙县小吃", calorie: 110, nutrients: { protein: 18, carb: 4, fat: 4 } },
  { name: "沙县炖罐-莲子猪肚汤", category: "沙县小吃", calorie: 105, nutrients: { protein: 16, carb: 5, fat: 3 } },
  { name: "沙县炖罐-当归排骨汤", category: "沙县小吃", calorie: 98, nutrients: { protein: 14, carb: 3, fat: 3 } },
  { name: "沙县豆腐脑", category: "沙县小吃", calorie: 45, nutrients: { protein: 5, carb: 3, fat: 2 } },
  { name: "沙县紫菜蛋花汤", category: "沙县小吃", calorie: 60, nutrients: { protein: 4, carb: 3, fat: 3 } },
  // 沙县小吃 - 面点类
  { name: "沙县拌面", category: "沙县小吃", calorie: 145, nutrients: { protein: 5, carb: 28, fat: 2 } },
  { name: "沙县花生酱拌面", category: "沙县小吃", calorie: 160, nutrients: { protein: 5, carb: 28, fat: 5 } },
  { name: "沙县葱油拌面", category: "沙县小吃", calorie: 150, nutrients: { protein: 5, carb: 27, fat: 4 } },
  { name: "沙县蒸饺", category: "沙县小吃", calorie: 120, nutrients: { protein: 8, carb: 15, fat: 4 } },
  { name: "沙县烧麦", category: "沙县小吃", calorie: 135, nutrients: { protein: 6, carb: 22, fat: 3 } },
  { name: "沙县锅贴", category: "沙县小吃", calorie: 180, nutrients: { protein: 9, carb: 16, fat: 9 } },
  // 沙县小吃 - 卤味单品
  { name: "沙县卤鸡腿", category: "沙县小吃", calorie: 195, nutrients: { protein: 20, carb: 3, fat: 10 } },
  { name: "沙县卤鸭腿", category: "沙县小吃", calorie: 200, nutrients: { protein: 18, carb: 3, fat: 12 } },
  { name: "沙县卤蛋", category: "沙县小吃", calorie: 110, nutrients: { protein: 10, carb: 1, fat: 8 } },
  { name: "沙县卤豆干", category: "沙县小吃", calorie: 75, nutrients: { protein: 10, carb: 3, fat: 4 } },
  { name: "沙县卤鸡爪", category: "沙县小吃", calorie: 185, nutrients: { protein: 12, carb: 2, fat: 15 } },
  // 沙县小吃 - 特色单品
  { name: "沙县炸馄饨", category: "沙县小吃", calorie: 220, nutrients: { protein: 10, carb: 15, fat: 13 } },
  { name: "沙县煎饺", category: "沙县小吃", calorie: 190, nutrients: { protein: 10, carb: 17, fat: 9 } },
  { name: "沙县炒米粉", category: "沙县小吃", calorie: 165, nutrients: { protein: 6, carb: 30, fat: 4 } },
  { name: "沙县蒸米粉", category: "沙县小吃", calorie: 140, nutrients: { protein: 5, carb: 28, fat: 2 } },
  { name: "沙县炸鸡腿", category: "沙县小吃", calorie: 215, nutrients: { protein: 14, carb: 10, fat: 14 } }
];

// 新增手动添加食物到数据库
function addFoodToDB(newFood) {
  // newFood格式：{ name: '', category: '自定义', calorie: 数值 }
  FOOD_DB.push(newFood);
  // 持久化存储到localStorage，避免刷新丢失
  localStorage.setItem('CUSTOM_FOOD_DB', JSON.stringify(FOOD_DB));
}

// 修改数据库中已存在的自定义食物
function editFoodInDB(foodName, newCalorie) {
  const targetFood = FOOD_DB.find(item => item.name === foodName && item.category === '自定义');
  if (targetFood) {
    targetFood.calorie = newCalorie;
    localStorage.setItem('CUSTOM_FOOD_DB', JSON.stringify(FOOD_DB));
  }
}

// 初始化时加载本地存储的自定义食物
window.onload = function() {
  const savedFood = localStorage.getItem('CUSTOM_FOOD_DB');
  if (savedFood) {
    // 合并存储的食物数据到FOOD_DB
    const savedFoodDB = JSON.parse(savedFood);
    FOOD_DB = savedFoodDB;
  }
};

// 导出食物数据库和操作函数
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { FOOD_DB, addFoodToDB, editFoodInDB };
}

// 确保全局可访问
window.FOOD_DB = FOOD_DB;
window.addFoodToDB = addFoodToDB;
window.editFoodInDB = editFoodInDB;